{{- if (eq .Values.proxysql_cluster.satellite.kind "Deployment") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "proxysql.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # Automatically Roll Deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "proxysql.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Chart.Name }}
          command: ["proxysql", "-c", "/etc/proxysql/proxysql.cnf", "-f"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: 6033
              protocol: TCP
            - name: admin
              containerPort: 6032
              protocol: TCP
            - name: web
              containerPort: 6080
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["bash", "-c", "true <>/dev/tcp/127.0.0.1/6033"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/proxysql
            - name: conf
              mountPath: /etc/proxysql/proxysql.cnf
              subPath: proxysql.cnf
            - name: secrets
              mountPath: /etc/proxysql/admin_credentials.cnf
              subPath: admin_credentials.cnf
          {{- if .Values.ssl.fromSecret }}
            - name: ssl
              mountPath: /etc/proxysql/ssl
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | int }}
      volumes:
        - name: data
          emptyDir: {}
        - name: secrets
          secret:
            secretName: {{ include "proxysql.fullname" . }}
            defaultMode: 0640
        - name: conf
          configMap:
            name: {{ include "proxysql.fullname" . }}
        {{- with .Values.ssl.fromSecret }}
        - name: ssl
          secret:
            secretName: {{ . }}
            defaultMode: 0640
        {{- end }}
{{- end }}
