debugMode: false
profiling:
  enabled: false
monitoring:
  enabled: true
single:
  enabled: true
  host: 0.0.0.0
  port: 8097
  name: pprof/monitoring server
  concurrency: 100000
  buffer:
    readBufferSize: 256KiB
    writeBufferSize: 256KiB
  tcpKeepalive:
    enabled: true
    period: 1s
  httptransport:
    maxIdleConnDuration: 15s
    readTimeout: 7s
    writeTimeout: 7s
controller:
  url: ""
  transport:
    maxIdleConns: 10
    buffer:
      readBufferSize: 256KiB
      writeBufferSize: 256KiB
    tcpKeepalive:
      enabled: false
      period: 15s
grpc:
  enabled: true
  useReflection: true
  compression:
    enabled: false
    type: Zstd
  connection:
    host: 0.0.0.0
    port: 8091
    readBufferSize: 50MiB
    writeBufferSize: 50MiB
    maxMessageSize: 50MiB
    insecure: true
    timeout: 15s
  keepalive:
    time: 5m
    timeout: 5m
    enforcementPolicy:
      minTime: 20m
      permitWithoutStream: false