apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  config.toml: |-
  {{- include (print $.Template.BasePath "/configs/_config.txt") . | nindent 4 }}
---
{{- if .Values.rsyncd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-rsyncd-config"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  rsyncd.conf: |-
  {{- include (print $.Template.BasePath "/configs/_rsyncd.txt") . | nindent 4 }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-env"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  {{- include (print $.Template.BasePath "/configs/_env.txt") . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-probe-env"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  env.txt: |-
  {{- include (print $.Template.BasePath "/configs/_probe-env.txt") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  check_node_health.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_check_node_health.tpl") . | nindent 4 }}
  check_node_readiness.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_check_node_readiness.tpl") . | nindent 4 }}
  get_nodekey.py: |-
    {{- include (print $.Template.BasePath "/scripts/_get_nodekey.tpl") . | nindent 4 }}
  get_nodekey_ip.py: |-
    {{- include (print $.Template.BasePath "/scripts/_get_nodekey_ip.tpl") . | nindent 4 }}
  generate_node_config.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_generate_node_config.tpl") . | nindent 4 }}
  init_from_snaphot.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_init_from_snaphot.tpl") . | nindent 4 }}
  init_from_rsync.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_init_from_rsync.tpl") . | nindent 4 }}
  init_from_gcs.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_init_from_gcs.tpl") . | nindent 4 }}
  sync_to_gcs.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_sync_to_gcs.tpl") . | nindent 4 }}
  gcs_cleanup.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_gcs_cleanup.tpl") . | nindent 4 }}
  prune.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_prune.tpl") . | nindent 4 }}
  cron.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_cron.tpl") . | nindent 4 }}
  update-pod-deletion-cost.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_update_pod_deletion_cost.tpl") . | nindent 4 }}
  controller-hook.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_controller_hook.tpl") . | nindent 4 }}
  rotate.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_rotate.tpl") . | nindent 4 }}
---
{{- if .Values.failback.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-nginx-config"
  labels: {{ include "bsc.labels" . | nindent 4 }}
data:
  nginx.conf: |-
  {{- include (print $.Template.BasePath "/configs/_nginx.txt") . | nindent 4 }}
---
{{- end }}
