apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  config.toml: |-
  {{- include (print $.Template.BasePath "/configs/_config.txt") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  check_node_health.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_check_node_health.tpl") . | nindent 4 }}
  check_node_readiness.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_check_node_readiness.tpl") . | nindent 4 }}
  get_nodekey.py: |-
    {{- include (print $.Template.BasePath "/scripts/_get_nodekey.tpl") . | nindent 4 }}
  init_from_snaphot.sh: |-
  {{- include (print $.Template.BasePath "/scripts/_init_from_snaphot.tpl") . | nindent 4 }}
---
{{- if .Values.failback.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-nginx-config"
data:
  nginx.conf: |-
  {{- include (print $.Template.BasePath "/configs/_nginx.txt") . | nindent 4 }}
---
{{- end }}
