debugMode: true
profiling:
  enabled: true
monitoring:
  enabled: true
single:
  enabled: true
  host: localhost
  port: 8097
  name: pprof/monitoring server
  concurrency: 100000
  buffer:
    readBufferSize: 4MiB
    writeBufferSize: 4MiB
  tcpKeepalive:
    enabled: true
    period: 1s
  httptransport:
    maxIdleConnDuration: 15s
    readTimeout: 7s
    writeTimeout: 7s
elasticsearch:
  client:
    address: http://localhost:9200
    username: ""
    password: ""
    maxRetries: 7
    transport:
      maxIdleConnDuration: 1m0s
      readTimeout: 7s
      writeTimeout: 7s
  processor:
    workersCount: 10
    flushBytes: 4KiB
    flushInterval: 30s
    indexTemplatePatternName: ai-scale
    batchTimeout: 1m
    bulkTimeout: 10s
grpc:
  enabled: true
  useReflection: true
  compression:
    enabled: false
    type: Zstd
  connection:
    host: localhost
    port: 8091
    readBufferSize: 100MiB
    writeBufferSize: 100MiB
    maxMessageSize: 30MiB
    insecure: true
    timeout: 15s
  keepalive:
    time: 5m
    timeout: 5m
    enforcementPolicy:
      minTime: 20m
      permitWithoutStream: false
