{{- with .Values.services.rpc }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "solana.fullname" $ }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: rpc
    {{- include "solana.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- if eq .type "LoadBalancer" }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  publishNotReadyAddresses: {{ .publishNotReadyAddresses }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ add .port 1 }}
      targetPort: ws
      protocol: TCP
      name: ws
    {{- if $.Values.plugins.enabled }}
    {{- if or $.Values.plugins.yellowstoneGRPC.enabled $.Values.plugins.jitoGRPC.enabled }}
    {{- toYaml $.Values.plugins.grpc.service_ports | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- with .extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "solana.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
