resources: []
#  - apiVersion: scheduling.k8s.io/v1beta1
#    kind: PriorityClass
#    metadata:
#      name: app-low
#    value: 70000
#    globalDefault: false
#    description: "This priority class should only be used for low priority app pods."

templates: []
#  - |
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: common-secret
#    stringData:
#      mykey: {{ .Values.mysecret }}
